### ISSUE TITLE
warning: unhandled enum value in switch statement

### ISSUE THREAD

**Issue by antis81** [cunz-rad/gnc#2]
Please have a look at `void ConnectionWindow::setState(State s)`. The `State::None` value is not handled -> produces a compiler warning.

**Comment by scunz** [comment]
Can't actually happen, but you're right. Again; no compiler warnings for such things with MSVC2015 :)

**Comment by antis81** [comment]
I keep my mouth shut and let that nasty :sleeping: :dog: alone. That beast needs to rescue himself. :) Totally excited about what the future brings though. Recent (political) development here seems appealing.
